[project]
name = 'Blockchain-Based-Spiritual-Development-Consciousness-Awakening-Acceleration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.awakening-protocol]
path = 'contracts/awakening-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.enlightenment-support]
path = 'contracts/enlightenment-support.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
